services:
  - type: web
    name: justificativas-fpa-piloto
    runtime: docker
    plan: 0.5c-512mb
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: GCP_PROJECT_ID
        value: vtal-fpea-prd
      - key: GCP_BUCKET_NAME
        value: vtal-bucket-financeiro-prd
      - key: GCP_SERVICE_ACCOUNT_KEY
        sync: false
